services:
  db:
    image: postgis/postgis:16-3.4
    container_name: alpine_ledger_db
    environment:
      POSTGRES_DB: alpine_ledger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d alpine_ledger"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
