jurisdictions:
  BC:
    tokens: ["British Columbia", "BC", "Coast Mountains", "Squamish", "Whistler", "Garibaldi",
      "Vancouver", "North Vancouver", "West Vancouver", "North Shore", "North Shore Mountains",
      "Grouse Mountain", "Cypress Mountain", "Mount Seymour", "Sea to Sky", "Pemberton",
      "Lions Bay", "Howe Sound", "Golden Ears", "Golden Ears Provincial Park", "Chilliwack",
      "Fraser Valley", "Coquihalla", "Manning Park", "Sunshine Coast"]
  AB:
    tokens: ["Alberta", "AB", "Banff", "Jasper", "Kananaskis", "Canmore", "Rockies",
      "Peter Lougheed Provincial Park", "K-Country", "Calgary", "Edmonton", "Lake Louise",
      "Bow Valley", "Spray Valley", "Highway 40", "Yamnuska", "Mount Yamnuska", "Ghost",
      "Waterton", "Castle Mountain", "Crowsnest Pass"]
  WA:
    tokens: ["Washington", "Washington State", "WA", "North Cascades", "Mount Rainier", "Rainier", "Mount Baker", "Baker", "Snohomish County", "Del Campo", "Del Campo Peak", "Monte Cristo"]

activities:
  alpinism: ["climber", "mountaineer", "alpinist", "mountaineering"]
  climbing: ["climber", "climbing", "rock climber", "rock climbing", "ice climber", "ice climbing", "mixed climbing"]
  hiking: ["hiker", "hiking", "backpacker", "trekker", "trekking"]
  scrambling: ["scrambler", "scrambling"]
  ski-mountaineering: [
    "skier",
    "snowboarder",
    "backcountry",
    "backcountry skiing",
    "backcountry snowboarding",
    "ski mountaineer",
    "ski touring",
    "ski tourer",
    "alpine touring",
    "AT skier",
    "splitboarder",
    "splitboarding",
    "skimo"
  ]

fatality_triggers:
  - death
  - died
  - dies
  - fatal
  - fatality
  - perished
  - killed
  - "lost their life"
  - "found dead"
  - "pronounced dead"
  - "recovery operation"
  - "body recovered"
  - "not recovered"

include_domains:
  - climbing.com
  - gripped.com
  - alpinist.com
  - avalanche.ca
  - gofundme.com
  - nps.gov
  - fs.usda.gov
  - mountaineers.org
  - cbc.ca
  - globalnews.ca

include_domains_by_jurisdiction:
  BC:
    - vancouversun.com
    - theprovince.com
    - squamishchief.com
    - castanet.net
    - coastreporter.net
    - northshorerescue.com
    - squamishsar.org
  AB:
    - calgaryherald.com
    - calgarysun.com
    - edmontonjournal.com
    - calgary.ctvnews.ca
    - edmonton.ctvnews.ca
  WA:
    - seattletimes.com
    - king5.com
    - komonews.com
    - heraldnet.com
    - bellinghamherald.com
    - fox13seattle.com
    - mountbakersar.org
    - seattlemountainrescue.org

exclude_domains:
  - insurancejournal.com
  - aol.com
  - foxnews.com
  - edition.cnn.com
  - cnn.com
  - usatoday.com
  - washingtonpost.com
  - theguardian.com
  - apnews.com
  - cbsnews.com

